export enum PRODUCT_ERROR {
  PRODUCT_WITH_THIS_ID_NOT_FOUND = "PRODUCT_WITH_THIS_ID_NOT_FOUND",
  PRODUCT_ALL_FIELDS_REQUIRED = "PRODUCT_ALL_FIELDS_REQUIRED",
  GUARD = "NO_NEEDED_DATA_IN_PARAMS",
  CREATE_PRODUCT_ITEM = "CREATE_PRODUCT_ITEM",
  UPDATE_PRODUCT_ITEM = "UPDATE_PRODUCT_ITEM",
}
