export enum PHOTO_ERROR {
  PHOTO_WITH_THIS_ID_NOT_FOUND = "PHOTO_WITH_THIS_ID_NOT_FOUND",
  PHOTO_ALL_FIELDS_REQUIRED = "PHOTO_ALL_FIELDS_REQUIRED",
  GUARD = "NO_NEEDED_DATA_IN_PARAMS",
  CREATE_PHOTO_ITEM = "CREATE_PHOTO_ITEM",
  UPDATE_PHOTO_ITEM = "UPDATE_PHOTO_ITEM",
}
